// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: api/proto/crypto.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Crypto_PushRates_FullMethodName        = "/crypto.Crypto/PushRates"
	Crypto_WaitNotification_FullMethodName = "/crypto.Crypto/WaitNotification"
)

// CryptoClient is the client API for Crypto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Crypto service manages price rate streaming and alert notifications
type CryptoClient interface {
	// PushRates pushes price ticks from the ingestion layer
	PushRates(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PriceTick, PushSummary], error)
	// WaitNotification sends request with target price from notification layer
	// and listens for alert notifications
	WaitNotification(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PriceTick], error)
}

type cryptoClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoClient(cc grpc.ClientConnInterface) CryptoClient {
	return &cryptoClient{cc}
}

func (c *cryptoClient) PushRates(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PriceTick, PushSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Crypto_ServiceDesc.Streams[0], Crypto_PushRates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PriceTick, PushSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Crypto_PushRatesClient = grpc.ClientStreamingClient[PriceTick, PushSummary]

func (c *cryptoClient) WaitNotification(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PriceTick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Crypto_ServiceDesc.Streams[1], Crypto_WaitNotification_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NotifyRequest, PriceTick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Crypto_WaitNotificationClient = grpc.ServerStreamingClient[PriceTick]

// CryptoServer is the server API for Crypto service.
// All implementations must embed UnimplementedCryptoServer
// for forward compatibility.
//
// Crypto service manages price rate streaming and alert notifications
type CryptoServer interface {
	// PushRates pushes price ticks from the ingestion layer
	PushRates(grpc.ClientStreamingServer[PriceTick, PushSummary]) error
	// WaitNotification sends request with target price from notification layer
	// and listens for alert notifications
	WaitNotification(*NotifyRequest, grpc.ServerStreamingServer[PriceTick]) error
	mustEmbedUnimplementedCryptoServer()
}

// UnimplementedCryptoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCryptoServer struct{}

func (UnimplementedCryptoServer) PushRates(grpc.ClientStreamingServer[PriceTick, PushSummary]) error {
	return status.Error(codes.Unimplemented, "method PushRates not implemented")
}
func (UnimplementedCryptoServer) WaitNotification(*NotifyRequest, grpc.ServerStreamingServer[PriceTick]) error {
	return status.Error(codes.Unimplemented, "method WaitNotification not implemented")
}
func (UnimplementedCryptoServer) mustEmbedUnimplementedCryptoServer() {}
func (UnimplementedCryptoServer) testEmbeddedByValue()                {}

// UnsafeCryptoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoServer will
// result in compilation errors.
type UnsafeCryptoServer interface {
	mustEmbedUnimplementedCryptoServer()
}

func RegisterCryptoServer(s grpc.ServiceRegistrar, srv CryptoServer) {
	// If the following call panics, it indicates UnimplementedCryptoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Crypto_ServiceDesc, srv)
}

func _Crypto_PushRates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CryptoServer).PushRates(&grpc.GenericServerStream[PriceTick, PushSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Crypto_PushRatesServer = grpc.ClientStreamingServer[PriceTick, PushSummary]

func _Crypto_WaitNotification_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NotifyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CryptoServer).WaitNotification(m, &grpc.GenericServerStream[NotifyRequest, PriceTick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Crypto_WaitNotificationServer = grpc.ServerStreamingServer[PriceTick]

// Crypto_ServiceDesc is the grpc.ServiceDesc for Crypto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Crypto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crypto.Crypto",
	HandlerType: (*CryptoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushRates",
			Handler:       _Crypto_PushRates_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WaitNotification",
			Handler:       _Crypto_WaitNotification_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/crypto.proto",
}
