// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: api/proto/crypto.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSummary) Reset() {
	*x = PushSummary{}
	mi := &file_api_proto_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSummary) ProtoMessage() {}

func (x *PushSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSummary.ProtoReflect.Descriptor instead.
func (*PushSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *PushSummary) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PriceTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceTick) Reset() {
	*x = PriceTick{}
	mi := &file_api_proto_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceTick) ProtoMessage() {}

func (x *PriceTick) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceTick.ProtoReflect.Descriptor instead.
func (*PriceTick) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *PriceTick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceTick) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TargetPrice   float64                `protobuf:"fixed64,2,opt,name=target_price,json=targetPrice,proto3" json:"target_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_api_proto_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *NotifyRequest) GetTargetPrice() float64 {
	if x != nil {
		return x.TargetPrice
	}
	return 0
}

var File_api_proto_crypto_proto protoreflect.FileDescriptor

const file_api_proto_crypto_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/crypto.proto\x12\x06crypto\"#\n" +
	"\vPushSummary\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"9\n" +
	"\tPriceTick\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\"J\n" +
	"\rNotifyRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\ftarget_price\x18\x02 \x01(\x01R\vtargetPrice2\x83\x01\n" +
	"\x06Crypto\x127\n" +
	"\tPushRates\x12\x11.crypto.PriceTick\x1a\x13.crypto.PushSummary\"\x00(\x01\x12@\n" +
	"\x10WaitNotification\x12\x15.crypto.NotifyRequest\x1a\x11.crypto.PriceTick\"\x000\x01B,Z*github.com/werastine/CryptoNotifier/pkg/pbb\x06proto3"

var (
	file_api_proto_crypto_proto_rawDescOnce sync.Once
	file_api_proto_crypto_proto_rawDescData []byte
)

func file_api_proto_crypto_proto_rawDescGZIP() []byte {
	file_api_proto_crypto_proto_rawDescOnce.Do(func() {
		file_api_proto_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_crypto_proto_rawDesc), len(file_api_proto_crypto_proto_rawDesc)))
	})
	return file_api_proto_crypto_proto_rawDescData
}

var file_api_proto_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_crypto_proto_goTypes = []any{
	(*PushSummary)(nil),   // 0: crypto.PushSummary
	(*PriceTick)(nil),     // 1: crypto.PriceTick
	(*NotifyRequest)(nil), // 2: crypto.NotifyRequest
}
var file_api_proto_crypto_proto_depIdxs = []int32{
	1, // 0: crypto.Crypto.PushRates:input_type -> crypto.PriceTick
	2, // 1: crypto.Crypto.WaitNotification:input_type -> crypto.NotifyRequest
	0, // 2: crypto.Crypto.PushRates:output_type -> crypto.PushSummary
	1, // 3: crypto.Crypto.WaitNotification:output_type -> crypto.PriceTick
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_crypto_proto_init() }
func file_api_proto_crypto_proto_init() {
	if File_api_proto_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_crypto_proto_rawDesc), len(file_api_proto_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_crypto_proto_goTypes,
		DependencyIndexes: file_api_proto_crypto_proto_depIdxs,
		MessageInfos:      file_api_proto_crypto_proto_msgTypes,
	}.Build()
	File_api_proto_crypto_proto = out.File
	file_api_proto_crypto_proto_goTypes = nil
	file_api_proto_crypto_proto_depIdxs = nil
}
